name: Release
description: Create github release

on: 
  pull_request:
    types: [closed]
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Get next version
        id: get_next_version
        uses: thenativeweb/get-next-version@main
        with:
          prefix: 'v'

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        if: steps.get_next_version.outputs.hasNextVersion == 'true'
        with:
          tag: ${{ steps.get_next_version.outputs.version }}
          name: Release ${{ steps.get_next_version.outputs.version }}
          body: "Automated release for PR #${{ github.event.pull_request.number }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}