name: Test
description: Run tests and code analysis on Python code using GitHub Actions

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint pytest
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files 'greetings/*.py')
    - name: Running tests with pytest
      run: |
        pytest --maxfail=1 --disable-warnings -q
